var store = {
  "xp": {
    "29": 0.1,
    "31": 3,
    "34": 3,
    "50": 6,
    "287": 1.5,
    "288": 2,
    "289": 2.5,
    "291": 10,
    "296": 5,
    "313": 1.5,
    "314": 1,
    "384": 15,
    "594": 10,
    "595": 18,
    "596": 25,
    "597": 35,
    "1014": 25
  },
  "floors":[
      {
         "id":0,
         "item_id":730,
         "level":1,
         "consumes":[
            {
               "id":29,
               "count":100
            }
         ],
         "craftable":true
      },
      {
         "id":1,
         "item_id":731,
         "level":10,
         "consumes":[
            {
               "id":314,
               "count":200
            }
         ],
         "craftable":true
      },
      {
         "id":2,
         "item_id":732,
         "level":25,
         "consumes":[
            {
               "id":313,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":3,
         "item_id":825,
         "level":35,
         "consumes":[
            {
               "id":296,
               "count":400
            }
         ],
         "craftable":true
      },
      {
         "id":4,
         "item_id":830,
         "level":45,
         "consumes":[
            {
               "id":594,
               "count":500
            }
         ],
         "craftable":true
      },
      {
         "id":5,
         "item_id":836,
         "level":55,
         "consumes":[
            {
               "id":595,
               "count":600
            }
         ],
         "craftable":true
      },
      {
         "id":6,
         "item_id":842,
         "level":65,
         "consumes":[
            {
               "id":596,
               "count":700
            }
         ],
         "craftable":true
      },
      {
         "id":7,
         "item_id":848,
         "level":80,
         "consumes":[
            {
               "id":597,
               "count":800
            }
         ],
         "craftable":true
      }
   ],
   "walls":[
      {
         "id":0,
         "item_id":734,
         "level":1,
         "consumes":[
            {
               "id":29,
               "count":200
            }
         ],
         "craftable":true
      },
      {
         "id":1,
         "item_id":740,
         "level":13,
         "consumes":[
            {
               "id":314,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":2,
         "item_id":746,
         "level":33,
         "consumes":[
            {
               "id":313,
               "count":400
            },
            {
               "id":34,
               "count":200
            }
         ],
         "craftable":true
      },
      {
         "id":3,
         "item_id":752,
         "level":45,
         "consumes":[
            {
               "id":50,
               "count":10
            },
            {
               "id":29,
               "count":50
            }
         ],
         "craftable":true
      },
      {
         "id":4,
         "item_id":824,
         "level":42,
         "consumes":[
            {
               "id":296,
               "count":600
            },
            {
               "id":34,
               "count":400
            }
         ],
         "craftable":true
      },
      {
         "id":5,
         "item_id":829,
         "level":52,
         "consumes":[
            {
               "id":594,
               "count":500
            },
            {
               "id":50,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":6,
         "item_id":835,
         "level":62,
         "consumes":[
            {
               "id":595,
               "count":600
            },
            {
               "id":50,
               "count":400
            }
         ],
         "craftable":true
      },
      {
         "id":7,
         "item_id":841,
         "level":74,
         "consumes":[
            {
               "id":596,
               "count":600
            },
            {
               "id":291,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":8,
         "item_id":847,
         "level":93,
         "consumes":[
            {
               "id":597,
               "count":500
            },
            {
               "id":384,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":9,
         "item_id":1357,
         "level":53,
         "consumes":[
            {
               "id":29,
               "count":300
            },
            {
               "id":313,
               "count":300
            },
            {
               "id":594,
               "count":300
            }
         ],
         "craftable":true
      }
   ],
   "furniture":[
      {
         "id":0,
         "item_id":753,
         "level":1,
         "consumes":[
            {
               "id":287,
               "count":35
            }
         ],
         "craftable":true
      },
      {
         "id":1,
         "item_id":753,
         "level":1,
         "consumes":[
            {
               "id":288,
               "count":25
            }
         ],
         "craftable":true
      },
      {
         "id":2,
         "item_id":733,
         "level":1,
         "consumes":[
            {
               "id":29,
               "count":20
            }
         ],
         "craftable":true
      },
      {
         "id":3,
         "item_id":735,
         "level":3,
         "consumes":[
            {
               "id":29,
               "count":75
            }
         ],
         "craftable":true
      },
      {
         "id":4,
         "item_id":736,
         "level":10,
         "consumes":[
            {
               "id":29,
               "count":30
            }
         ],
         "craftable":true
      },
      {
         "id":5,
         "item_id":737,
         "level":6,
         "consumes":[
            {
               "id":29,
               "count":140
            }
         ],
         "craftable":true
      },
      {
         "id":6,
         "item_id":738,
         "level":8,
         "consumes":[
            {
               "id":29,
               "count":150
            }
         ],
         "craftable":true
      },
      {
         "id":7,
         "item_id":739,
         "level":10,
         "consumes":[
            {
               "id":314,
               "count":20
            }
         ],
         "craftable":true
      },
      {
         "id":8,
         "item_id":741,
         "level":14,
         "consumes":[
            {
               "id":314,
               "count":75
            }
         ],
         "craftable":true
      },
      {
         "id":9,
         "item_id":742,
         "level":25,
         "consumes":[
            {
               "id":314,
               "count":50
            }
         ],
         "craftable":true
      },
      {
         "id":10,
         "item_id":743,
         "level":24,
         "consumes":[
            {
               "id":314,
               "count":200
            }
         ],
         "craftable":true
      },
      {
         "id":11,
         "item_id":744,
         "level":20,
         "consumes":[
            {
               "id":314,
               "count":150
            }
         ],
         "craftable":true
      },
      {
         "id":12,
         "item_id":745,
         "level":25,
         "consumes":[
            {
               "id":313,
               "count":20
            }
         ],
         "craftable":true
      },
      {
         "id":13,
         "item_id":747,
         "level":28,
         "consumes":[
            {
               "id":313,
               "count":75
            }
         ],
         "craftable":true
      },
      {
         "id":14,
         "item_id":748,
         "level":35,
         "consumes":[
            {
               "id":313,
               "count":60
            }
         ],
         "craftable":true
      },
      {
         "id":15,
         "item_id":749,
         "level":34,
         "consumes":[
            {
               "id":313,
               "count":200
            }
         ],
         "craftable":true
      },
      {
         "id":16,
         "item_id":750,
         "level":30,
         "consumes":[
            {
               "id":313,
               "count":150
            }
         ],
         "craftable":true
      },
      {
         "id":17,
         "item_id":768,
         "level":35,
         "consumes":[
            {
               "id":296,
               "count":30
            }
         ],
         "craftable":true
      },
      {
         "id":18,
         "item_id":769,
         "level":45,
         "consumes":[
            {
               "id":594,
               "count":30
            }
         ],
         "craftable":true
      },
      {
         "id":19,
         "item_id":770,
         "level":55,
         "consumes":[
            {
               "id":595,
               "count":30
            }
         ],
         "craftable":true
      },
      {
         "id":20,
         "item_id":771,
         "level":65,
         "consumes":[
            {
               "id":596,
               "count":40
            }
         ],
         "craftable":true
      },
      {
         "id":21,
         "item_id":772,
         "level":80,
         "consumes":[
            {
               "id":597,
               "count":50
            }
         ],
         "craftable":true
      },
      {
         "id":22,
         "item_id":826,
         "level":37,
         "consumes":[
            {
               "id":296,
               "count":75
            }
         ],
         "craftable":true
      },
      {
         "id":23,
         "item_id":853,
         "level":40,
         "consumes":[
            {
               "id":296,
               "count":150
            }
         ],
         "craftable":true
      },
      {
         "id":24,
         "item_id":827,
         "level":45,
         "consumes":[
            {
               "id":296,
               "count":70
            }
         ],
         "craftable":true
      },
      {
         "id":25,
         "item_id":828,
         "level":44,
         "consumes":[
            {
               "id":296,
               "count":250
            }
         ],
         "craftable":true
      },
      {
         "id":26,
         "item_id":831,
         "level":49,
         "consumes":[
            {
               "id":594,
               "count":105
            }
         ],
         "craftable":true
      },
      {
         "id":27,
         "item_id":832,
         "level":55,
         "consumes":[
            {
               "id":594,
               "count":80
            }
         ],
         "craftable":true
      },
      {
         "id":28,
         "item_id":833,
         "level":54,
         "consumes":[
            {
               "id":594,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":29,
         "item_id":834,
         "level":50,
         "consumes":[
            {
               "id":594,
               "count":210
            }
         ],
         "craftable":true
      },
      {
         "id":30,
         "item_id":837,
         "level":58,
         "consumes":[
            {
               "id":595,
               "count":105
            }
         ],
         "craftable":true
      },
      {
         "id":31,
         "item_id":840,
         "level":60,
         "consumes":[
            {
               "id":595,
               "count":210
            }
         ],
         "craftable":true
      },
      {
         "id":32,
         "item_id":839,
         "level":64,
         "consumes":[
            {
               "id":595,
               "count":400
            }
         ],
         "craftable":true
      },
      {
         "id":33,
         "item_id":838,
         "level":65,
         "consumes":[
            {
               "id":595,
               "count":90
            }
         ],
         "craftable":true
      },
      {
         "id":34,
         "item_id":843,
         "level":70,
         "consumes":[
            {
               "id":596,
               "count":150
            }
         ],
         "craftable":true
      },
      {
         "id":35,
         "item_id":844,
         "level":80,
         "consumes":[
            {
               "id":596,
               "count":100
            }
         ],
         "craftable":true
      },
      {
         "id":36,
         "item_id":845,
         "level":78,
         "consumes":[
            {
               "id":596,
               "count":500
            }
         ],
         "craftable":true
      },
      {
         "id":37,
         "item_id":846,
         "level":70,
         "consumes":[
            {
               "id":596,
               "count":300
            }
         ],
         "craftable":true
      },
      {
         "id":38,
         "item_id":849,
         "level":83,
         "consumes":[
            {
               "id":597,
               "count":180
            }
         ],
         "craftable":true
      },
      {
         "id":39,
         "item_id":850,
         "level":95,
         "consumes":[
            {
               "id":597,
               "count":120
            }
         ],
         "craftable":true
      },
      {
         "id":40,
         "item_id":851,
         "level":98,
         "consumes":[
            {
               "id":597,
               "count":800
            }
         ],
         "craftable":true
      },
      {
         "id":41,
         "item_id":852,
         "level":90,
         "consumes":[
            {
               "id":597,
               "count":360
            }
         ],
         "craftable":true
      },
      {
         "id":42,
         "item_id":1129,
         "level":1,
         "craftable":false
      },
      {
         "id":43,
         "item_id":1130,
         "level":1,
         "craftable":false
      },
      {
         "id":44,
         "item_id":1131,
         "level":1,
         "consumes":[
            {
               "id":31,
               "count":250
            },
            {
               "id":1138,
               "count":1
            }
         ],
         "craftable":true
      },
      {
         "id":45,
         "item_id":1132,
         "level":1,
         "craftable":false
      },
      {
         "id":46,
         "item_id":1133,
         "level":1,
         "craftable":false
      },
      {
         "id":47,
         "item_id":1134,
         "level":1,
         "craftable":false
      },
      {
         "id":48,
         "item_id":1135,
         "level":1,
         "craftable":false
      },
      {
         "id":49,
         "item_id":1136,
         "level":1,
         "craftable":false
      },
      {
         "id":50,
         "item_id":1137,
         "level":1,
         "craftable":false
      },
      {
         "id":51,
         "item_id":1165,
         "level":1,
         "consumes":[
            {
               "id":1014,
               "count":10
            },
            {
               "id":50,
               "count":50
            }
         ],
         "craftable":true
      },
      {
         "id":52,
         "item_id":1165,
         "level":1,
         "consumes":[
            {
               "id":1012,
               "count":30
            },
            {
               "id":50,
               "count":50
            }
         ],
         "craftable":true
      },
      {
         "id":53,
         "item_id":1243,
         "level":50,
         "consumes":[
            {
               "id":29,
               "count":300
            },
            {
               "id":758,
               "count":100
            },
            {
               "id":760,
               "count":100
            }
         ],
         "craftable":true
      },
      {
         "id":54,
         "item_id":1360,
         "level":48,
         "consumes":[
            {
               "id":594,
               "count":50
            },
            {
               "id":50,
               "count":100
            }
         ],
         "craftable":true
      },
      {
         "id":55,
         "item_id":753,
         "level":1,
         "consumes":[
            {
               "id":289,
               "count":15
            }
         ],
         "craftable":true
      }
   ]
};
module.exports = store;
